// 365 Romantic Turkish quotes — one per day
// Indexed 0-364, selected by dayOfYear % 365

export const ROMANTIC_QUOTES: string[] = [
  "Seninle her gün daha çok seviyorum seni.",
  "Gözlerin, benim için en güzel ışık.",
  "Sen olmadan bir gün bile düşünemiyorum.",
  "Seninle geçirdiğim her an hazineden değerli.",
  "Kalbin attığında benimki de seninle atıyor.",
  "Seni sevmek, nefes almak kadar doğal.",
  "Her sabah gözlerimi açtığımda ilk düşündüğüm sensin.",
  "Sesini duymak, en güzel melodi benim için.",
  "Seninle olmak, evde olmak demek.",
  "Gülüşün, en karanlık günümü aydınlatıyor.",
  "Sen benim en büyük şansım ve en güzel kaderim.",
  "Seni seviyorum; dün de, bugün de, her zaman.",
  "Yanımda olduğunda dünya daha güzel görünüyor.",
  "Her bakışında yeniden aşık oluyorum sana.",
  "Sen benim için her şeysin; geçmişim, bugünum, geleceğim.",
  "Seninle yaşadığım her an, kalbimde sonsuza kadar yaşayacak.",
  "Seni düşünmek, en sevdiğim hobim oldu.",
  "Elini tuttuğumda tüm endişelerim uçup gidiyor.",
  "Sen benim kalbimin en gizli sayfasısın.",
  "Birlikte güldüğümüz anlarda, hayat daha manalı.",
  "Seni sevmek, hayatımın en doğru kararı.",
  "Gözlerin, anlatmaya sözcük bulamadığım bir şiir.",
  "Sen varken her gün sevgililer günü.",
  "Kalbim seninle konuştuğunda kelimeler yetmez.",
  "Her fısıltın, ruhuma işliyor.",
  "Seninle olan her hatıram, kalbimin en değerli hazinesi.",
  "Seni düşündükçe yüzümde gülümseme beliriyor.",
  "Yanında olduğumda zaman nasıl geçiyor anlamıyorum.",
  "Sen benim için eşsizsin; kimse seni yerini alamaz.",
  "Seninle uykuya dalmak, en huzurlu an.",
  "Gülüşün, tüm kederi alıp götürüyor.",
  "Seni sevdikçe, sevinç içimde büyüyor.",
  "Ellerini tuttuğumda, her şey yerli yerine oturuyor.",
  "Sen benim güneşimsin; hayatıma ışık ve sıcaklık getiriyorsun.",
  "Seninle yaşadığım her küçük an, büyük mutluluklar taşıyor.",
  "Kalbim seni çağırıyor, her attığında.",
  "Seninle olmak, en büyük maceram.",
  "Bakışların, sözcüksüz binlerce şey anlatıyor.",
  "Seni sevmek, en kolay ve en güzel şey.",
  "Seninle geçen her gün, ömrüme ömür katıyor.",
  "Sen olmadan, bu hayat yarım kalır.",
  "Seninle her şey daha anlamlı, her yer daha güzel.",
  "Kalbindeki sevgi, benim en büyük zenginliğim.",
  "Seni düşünmek, yorgunluğumu bir anda alıp götürüyor.",
  "Seninle her gün yeni bir başlangıç.",
  "Gözlerin kapalıyken bile seni hissediyorum.",
  "Sen benim en güzel rüyamsın.",
  "Seninle konuşmak, ruhuma iyi geliyor.",
  "Her sabah seninle daha mutlu uyanıyorum.",
  "Seni sevmek, kalbimin en güzel ritmi.",
  "Sen varken korkacak hiçbir şey yok.",
  "Seninle güvenli, seninle huzurlu, seninle tam.",
  "Seni seviyorum; şimdi, burada ve her zaman.",
  "Seninle geçirdiğim her dakika, değer biçilmez.",
  "Sen benim için mükemmelsin; tıpkı olduğun gibi.",
  "Seninle olan hikayemiz, en sevdiğim hikaye.",
  "Seni düşünmek, kalbimi ısıtıyor.",
  "Gülümsemen, günümü kurtarıyor.",
  "Seninle olmak, hayatımın en büyük lütfu.",
  "Seni sevdikçe, daha da çok seviyorum.",
  "Kalbim sana ait; şimdi ve sonsuza dek.",
  "Seninle her mevsim güzel.",
  "Seni sevmek, en büyük başarım.",
  "Sen benim için dünyanın en güzel armağanısın.",
  "Seninle her anın tadını çıkarıyorum.",
  "Gözlerinin içinde kaybolmak istiyorum.",
  "Seni düşünmek, bir güzellik içimde açıyor.",
  "Seninle olmak, en doğru seçimim.",
  "Her gün seninle daha çok büyüyorum.",
  "Sen benim kalbimin sesi, ruhumun yankısısın.",
  "Seninle her şey mümkün.",
  "Seni seviyorum; sözcükler yetmese de.",
  "Seninle geçen zaman, en değerli zamanım.",
  "Gözlerin, her şeyi anlatıyor bana.",
  "Seninle olmak, nefes almak gibi.",
  "Seni sevmek, kalbimde yankılanıyor.",
  "Seninle mutlu olmak, en büyük dileğim.",
  "Sen benim için dünyanın merkezi.",
  "Seninle geçirdiğim her gece, sabaha kadar gülümsüyorum.",
  "Seni seviyorum; tüm benliğimle.",
  "Kalbim seninle, her an, her yerde.",
  "Sen benim için biriciksin.",
  "Seninle hayat, bir sanat eseri gibi.",
  "Seni düşündükçe içim aydınlanıyor.",
  "Seninle olmak, en güzel varolma biçimim.",
  "Seni sevmek, hayatımın en anlamlı eylemi.",
  "Gülüşün, beni hayata bağlıyor.",
  "Seninle her zorluk daha kolay.",
  "Sen benim için sonsuzluğun anlamısın.",
  "Seninle olan her an, kalbimde iz bırakıyor.",
  "Seni seviyorum; bu kadar basit, bu kadar derin.",
  "Seninle geçen her gün, bir şiir gibi.",
  "Gözlerin, benim en güzel manzaram.",
  "Seninle olmak, en büyük şansım.",
  "Seni sevmek, içimde bir çiçek gibi açıyor.",
  "Sen benim için her şeyin başı ve sonu.",
  "Seninle her anı yaşamak istiyorum.",
  "Kalbim seni çağırıyor, durmadan.",
  "Seni seviyorum; düne de, bugüne de, yarına da.",
  "Seninle olmak, en güzel his.",
  "Sen benim için vazgeçilmezsin.",
  "Seninle her gün, yeni bir aşkın başlangıcı.",
  "Seni düşündükçe kalbim hafifliyor.",
  "Seninle olmak, en büyük huzurum.",
  "Gülüşün, en güzel müzik.",
  "Seni sevmek, her şeyi daha güzel yapıyor.",
  "Sen benim için mucivedir.",
  "Seninle geçirdiğim her gün, bir armağan.",
  "Kalbim sana, ruhum sana ait.",
  "Seni seviyorum; sonsuz ve koşulsuz.",
  "Seninle olan her bakışta, bir dünya kuruluyor.",
  "Sen benim için, hayatın kendisisin.",
  "Seninle her şey daha renkli.",
  "Seni düşünmek, kalbimi güldürüyor.",
  "Seninle olmak, en büyük ödülüm.",
  "Seni sevmek, ruhumu besliyor.",
  "Gözlerin, benim için en değerli hazine.",
  "Seninle her an, ömrümün en güzel sayfası.",
  "Sen benim için, eşsiz bir hazinesin.",
  "Seninle geçirdiğim her gece, sabaha dek gülümsüyorum.",
  "Kalbim, seninle daha güçlü atıyor.",
  "Seni seviyorum; kelimeler bu sevgiyi anlatmaya yetmez.",
  "Seninle olmak, en büyük lüksüm.",
  "Seni düşündüğümde, dünya durmuş gibi oluyor.",
  "Seninle her yer güzel.",
  "Sen benim için, her şeyin anlamısın.",
  "Seni sevmek, içimde yankılanıyor.",
  "Seninle olmak, hayatımın en büyük nimeti.",
  "Gülüşün, kalbimi ısıtıyor.",
  "Seni seviyorum; her geçen gün daha fazla.",
  "Sen benim için, en güzel rüya.",
  "Seninle geçen her dakika, ömrüme değer katıyor.",
  "Kalbim, seninle tam.",
  "Seni düşündükçe, içim coşuyor.",
  "Seninle olmak, en büyük mutluluğum.",
  "Seni sevmek, hayatımın en güzel kısmı.",
  "Gözlerin, kalbime dokunan en güzel şey.",
  "Seninle her gün, yeni bir aşk masalı.",
  "Sen benim için, en özel insan.",
  "Seninle geçirdiğim her an, sonsuzluğu taşıyor.",
  "Kalbim sana adanmış, tamamen.",
  "Seni seviyorum; şimdi ve her zaman.",
  "Seninle olmak, en güzel gerçekliğim.",
  "Seni düşünmek, en keyifli zaman.",
  "Seninle her şey mümkün, her şey güzel.",
  "Gülüşün, en büyük ödülüm.",
  "Seni sevmek, en doğal eylemim.",
  "Sen benim için, hayatımın şiirisin.",
  "Seninle geçen her gün, kalbimde iz bırakıyor.",
  "Kalbim, seninle daha mutlu.",
  "Seni seviyorum; bu his asla değişmeyecek.",
  "Seninle olmak, en büyük zenginliğim.",
  "Seni düşündükçe, gülümsemek kaçınılmaz.",
  "Seninle her yer, daha anlamlı.",
  "Gözlerin, bana hep umut veriyor.",
  "Seni sevmek, içimde bir ışık gibi parlıyor.",
  "Sen benim için, en güzel varlık.",
  "Seninle geçirdiğim her an, özel.",
  "Kalbim, seninle şarkı söylüyor.",
  "Seni seviyorum; bu gerçeği hiç değiştirmek istemiyorum.",
  "Seninle olmak, en güzel var oluş.",
  "Seni düşünmek, beni huzura kavuşturuyor.",
  "Seninle her yol, güzel.",
  "Gülüşün, en büyük motivasyonum.",
  "Seni sevmek, hayatımı anlamlı kılıyor.",
  "Sen benim için, tek ve eşsizsin.",
  "Seninle geçen her gece, sabaha kadar huzur içindeyim.",
  "Kalbim, seni her geçen gün daha çok seviyor.",
  "Seni seviyorum; geçmişte, şimdi ve gelecekte.",
  "Seninle olmak, en büyük armağan.",
  "Seni düşündükçe, dünya daha güzel.",
  "Seninle her an, anlamlı.",
  "Gözlerin, benim için kapıları açıyor.",
  "Seni sevmek, ruhumu zenginleştiriyor.",
  "Sen benim için, hayatımın kılavuzusun.",
  "Seninle geçirdiğim her gün, ömrümün en değerlisi.",
  "Kalbim, seninle huzurlu.",
  "Seni seviyorum; bu kelimeler az bile.",
  "Seninle olmak, en büyük ayrıcalığım.",
  "Seni düşünmek, içimi aydınlatıyor.",
  "Seninle her şey, daha anlamlı ve değerli.",
  "Gülüşün, en güzel armağan.",
  "Seni sevmek, hayatımın en büyük onuru.",
  "Sen benim için, her şeyin ötesinde bir değersin.",
  "Seninle geçen her an, sonsuzluğa değer.",
  "Kalbim, seninle tam ve huzurlu.",
  "Seni seviyorum; bu his bitmez, bitmeyecek.",
  "Seninle olmak, en büyük güven.",
  "Seni düşündükçe, kalbim genişliyor.",
  "Seninle her gün, daha güçlü oluyorum.",
  "Gözlerin, en güzel şiiri anlatıyor.",
  "Seni sevmek, en büyük dileğim gerçek oldu.",
  "Sen benim için, hayatımın en güzel bölümüsün.",
  "Seninle geçirdiğim her an, altın gibi.",
  "Kalbim, seninle dans ediyor.",
  "Seni seviyorum; dağlar kadar, denizler kadar.",
  "Seninle olmak, her şeyi mümkün kılıyor.",
  "Seni düşünmek, en güzel kaçış.",
  "Seninle her yer, cennete dönüşüyor.",
  "Gülüşün, en büyük enerji kaynağım.",
  "Seni sevmek, en güzel bağlılık.",
  "Sen benim için, bu hayatın anlamısın.",
  "Seninle geçen her gün, bir mucize.",
  "Kalbim, seninle her an daha çok açılıyor.",
  "Seni seviyorum; bu his, ruhuma işlemiş.",
  "Seninle olmak, en büyük hazzım.",
  "Seni düşündükçe, kalbim coşuyor.",
  "Seninle her adım, daha hafif.",
  "Gözlerin, bana yol gösteriyor.",
  "Seni sevmek, en doğal hislerimden biri.",
  "Sen benim için, her şeyin başlangıcısın.",
  "Seninle geçirdiğim her gün, kalbimde iz bırakıyor.",
  "Kalbim, seninle güçlü.",
  "Seni seviyorum; bu his, beni tamamlıyor.",
  "Seninle olmak, en büyük neşem.",
  "Seni düşünmek, beni hayata bağlıyor.",
  "Seninle her yer, daha ferah.",
  "Gülüşün, beni her zaman güldürüyor.",
  "Seni sevmek, hayatımın özüdür.",
  "Sen benim için, en değerli insan.",
  "Seninle geçen her an, bir şükran kaynağı.",
  "Kalbim, seninle özgür.",
  "Seni seviyorum; bu kelimelerle yetinmek zorundayım.",
  "Seninle olmak, en güzel alışkanlığım.",
  "Seni düşündükçe, içim dolup taşıyor.",
  "Seninle her yol, daha kısa.",
  "Gözlerin, benim için en derin deniz.",
  "Seni sevmek, beni daha iyi biri yapıyor.",
  "Sen benim için, hayatımın kahramanısın.",
  "Seninle geçirdiğim her gün, bir şans.",
  "Kalbim, seninle dolu.",
  "Seni seviyorum; bu his, sonsuza uzanıyor.",
  "Seninle olmak, en büyük servetim.",
  "Seni düşünmek, en güzel teselli.",
  "Seninle her şey, daha canlı.",
  "Gülüşün, en büyük moral kaynağım.",
  "Seni sevmek, ruhumu dinlendiriyor.",
  "Sen benim için, hayatımın güneşisin.",
  "Seninle geçen her an, bir güzellik barındırıyor.",
  "Kalbim, seninle sevinçle dolu.",
  "Seni seviyorum; bu gerçek, asla değişmeyecek.",
  "Seninle olmak, en büyük sığınağım.",
  "Seni düşündükçe, kalbim ısınıyor.",
  "Seninle her zorluk, daha kolay aşılıyor.",
  "Gözlerin, bana umut veriyor.",
  "Seni sevmek, hayatımın en büyük neşesi.",
  "Sen benim için, her şeyin güzeli.",
  "Seninle geçirdiğim her an, özel ve eşsiz.",
  "Kalbim, seninle her gün daha büyüyor.",
  "Seni seviyorum; bu sevgi, büyüyüp gelişiyor.",
  "Seninle olmak, en güzel seçimim.",
  "Seni düşünmek, en tatlı meşguliyet.",
  "Seninle her gün, yeni bir macera.",
  "Gülüşün, en güzel ses.",
  "Seni sevmek, hayatıma renk katıyor.",
  "Sen benim için, hayatımın şiirisin.",
  "Seninle geçen her gün, bir nimet.",
  "Kalbim, seninle hep genç.",
  "Seni seviyorum; bu his, bitmez tükenmez.",
  "Seninle olmak, en büyük şükranım.",
  "Seni düşündükçe, dünya güzelleşiyor.",
  "Seninle her an, değerli.",
  "Gözlerin, beni hep büyülüyor.",
  "Seni sevmek, içimde bir ateş yakıyor.",
  "Sen benim için, her şeyin ötesindesin.",
  "Seninle geçirdiğim her gece, huzur dolu.",
  "Kalbim, seninle sürekli şarkı söylüyor.",
  "Seni seviyorum; tüm varlığımla.",
  "Seninle olmak, en büyük varoluş amacım.",
  "Seni düşünmek, beni huzurlu kılıyor.",
  "Seninle her şey, mükemmel.",
  "Gülüşün, her şeyi iyileştiriyor.",
  "Seni sevmek, hayatımın en güzel anlamı.",
  "Sen benim için, en değerli armağan.",
  "Seninle geçen her an, ebediyete değer.",
  "Kalbim, seninle hep aşkla dolu.",
  "Seni seviyorum; bu his, kalbimin en derin yerinde.",
  "Seninle olmak, en büyük mutluluğum ve huzurum.",
  "Seni düşündükçe, kalbim şükranla dolup taşıyor.",
  "Seninle her gün, bir hediyedir.",
  "Gözlerin, benim için sonsuzluk.",
  "Seni sevmek, hayatımın en doğal parçası.",
  "Sen benim için, her şeyin özüsün.",
  "Seninle geçirdiğim her an, altından değerli.",
  "Kalbim, seninle sonsuza dek.",
  "Seni seviyorum; bu kelimeler az kalsa da, his sonsuz.",
];

/**
 * Returns the quote for a given day-of-year index
 */
export function getQuoteForDay(dayOfYear: number): string {
  const index = (dayOfYear - 1) % ROMANTIC_QUOTES.length;
  return ROMANTIC_QUOTES[index];
}
